name: iborrow
description: "iBorrow - A mobile library management app with Flutter and Supabase"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # State management
  provider: ^6.1.2
  equatable: ^2.0.5

  # UI components
  flutter_svg: ^2.0.12

  # Supabase for backend
  supabase_flutter: ^2.3.4

  # Local storage
  shared_preferences: ^2.3.3

  # Network
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
